### ISSUE TITLE
Support OIDC

### ISSUE THREAD

**Issue by hibare** [thomiceli/opengist#9] opened 2023-04-15 10:35 UTC
Thank you for the awesome project!!.

I was actually looking for GitHub gist alternatives for some time.
It would be wonderful if Opengist supports OIDC for SSO.

**Comment by thomiceli** [comment] 2023-04-16 23:05
Thank you! I will look into that

**Comment by poVoq** [comment] 2023-04-17 22:01
Duplicate of this: https://github.com/thomiceli/opengist/issues/3 I guess.

Although full OIDC support and not just OAuth2 could be added.

**Comment by Maronato** [comment] 2023-09-27 22:43
@thomiceli this can probably be closed now

**Closed** 2023-09-28 12:46 UTC
Labels: enhancement
